---
- hosts: cysista_proxy
  become: true
  gather_facts: no
  roles:
    - role: frps
      vars:
        key_name: cysista-proxy/frps
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      register: selinux
    - name: Reboot
      ansible.builtin.reboot:
      when: selinux.reboot_required
